[phases.setup]
nixPkgs = ["gcc", "python312"]

[phases.install]
cmds = ["python -m venv .venv && source .venv/bin/activate && pip install ."]

[start]
cmd = "source .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000"
