from ..contexts.calculation import CalculationContext
from .western import WesternModule
from .vedic import VedicModule
from .mundane import MundaneModule
from .research import ResearchModule


class AstroSDKClient:
    """
    Unified entry point for the AstroSDK 2.0 Python Surface.
    Provides a library-like experience for results generated by the 2.0 engine.
    """

    def __init__(self, context: CalculationContext | None = None) -> None:
        self.context = context or CalculationContext()
        
        # Initialize domains
        self.western = WesternModule(self.context)
        self.vedic = VedicModule(self.context)
        self.mundane = MundaneModule(self.context)
        self.research = ResearchModule(self.context)

    @property
    def config(self) -> CalculationContext:
        """Access the current calculation context."""
        return self.context
